### ISSUE TITLE
Injecting a deno map, breaks

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm#118] opened 2023-01-04 16:53 UTC
Replication:

```
jspm install @babel/core --env deno
jspm inject @babel/core test.html --env browser,production
```

Creates a `process.ts` mapping in the import map which doesn't execute.

**Comment by Aslemammad** [comment] 2023-01-08 15:18
I do not know what is the reason and the cause for this. Maybe it's an upstream issue?

**Comment by guybedford** [comment] 2023-01-08 15:54
Yes it could be a generator bug, perhaps try create a failing test PR for the generator at least?

**Comment by Aslemammad** [comment] 2023-01-08 19:08
sure, meanwhile, it'd be good if you'd review the PR. Thank you so much.

**Comment by Aslemammad** [comment] 2023-01-08 20:40
https://github.com/jspm/generator/pull/193

**Comment by Aslemammad** [comment] 2023-01-11 07:33
Let's close this as an upstream issue.

**Closed by Aslemammad** 2023-01-11 07:33 UTC
